// examples/Web Apps/Framework Examples/Angular/SystemLinkAuthExample/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { environment } from '../environments/environment';

const systemLinkServerUrl = environment.systemLinkServerUrl;

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    standalone: false,
    styleUrl: './app.component.scss'
})
export class AppComponent {
    public apiResponse = '';

    constructor(private readonly http: HttpClient) {}

    public handleClick(): void {
        this.http.get(`${systemLinkServerUrl}/niauth/v1/auth`)
            .subscribe({
                next: data => {
                    this.apiResponse = JSON.stringify(data, null, 2);
                },
                error: err => {
                    if (err instanceof Error) {
                        this.apiResponse = err.message;
                    } else {
                        this.apiResponse = String(err);
                    }
                }
            });
    }
}





            <div class="page">
                <div class="header">
                    <a
                        class="github"
                        href="https://github.com/ni/systemlink-enterprise-examples/examples/Web Apps/Framework Examples/Angular/SystemLinkAuthExample/"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span class="title">GitHub</span>
                        <span class="head_text">
                            Link to the GitHub repository with the source code and
                            instructions how to create and use it
                        </span>
                    </a>

                    <a
                        class="Numble"
                        href="https://nimble.ni.dev/"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span class="title">Nimble Design System</span>
                        <span class="head_text">
                            Library with the Nimble components
                        </span>
                    </a>

                    <a
                        class="Swagger"
                        href=" https://www.ni.com/docs/en-US/bundle/systemlink-api/page/http-api-reference.html"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span class="title">SystemLink APIs</span>
                        <span class="head_text">
                            Link to the documentation for all SystemLink API calls
                        </span>
                    </a>

                    <a
                        class="npm"
                        href="https://www.npmjs.com/package/@ni/nimble-angular"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span class="title">NPM Nimble</span>
                        <span class="head_text">
                            Link to the npm package for Nimble Angular components
                        </span>
                    </a>

                    <a
                        class="CLI"
                        href="https://github.com/ni-kismet/systemlink-cli"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span class="title">SystemLink CLI</span>
                        <span class="head_text">
                            Link to the GitHub instructions on how to use the CLI
                        </span>
                    </a>
                </div>

                <div class="content">
                    <div class="button_and_title">
                        <nimble-button appearance-variant="accent" class="button" (click)="handleClick()">
                          Make API call
                        </nimble-button>
                    </div>

                    <h2 class="API_title">API call example</h2>

                    <div class="main_description">
                        <div class="API">
                            <div class="API_method_and_path">
                                <span class="method">GET</span>
                                <h3 class="path">/auth</h3>
                            </div>
                            <div>
                                <span class="API_description_title">
                                    Authenticates API Keys
                                </span>
                            </div>
                            <div class="API_description">
                                <span class="API_text">
                                    The example makes an HTTP GET request to a SystemLink API and
                                    displays the result on the page. This specific API
                                    Authenticates the given x-ni-api-key and returns information
                                    about the call.
                                </span>
                            </div>
                            <div class="API_response">{{ apiResponse }}</div>
                        </div>
                    </div>
                </div>
            </div>
<router-outlet></router-outlet>

// examples/Web Apps/Framework Examples/React/ApiKeyAuthApp/src/App.tsx
import { NimbleButton } from '@ni/nimble-react/button';
import { useState } from 'react';
import './App.scss';

const systemLinkServerUrl = import.meta.env.VITE_SYSTEMLINK_SERVER_URL;

export function App(): React.JSX.Element {
    const [apiResponse, setApiResponse] = useState('');

    const handleClick: () => void = () => {
        fetch(`${systemLinkServerUrl}/niauth/v1/auth`)
            .then(async res => {
                const data: unknown = await res.json();
                return data;
            })
            .then(data => {
                setApiResponse(JSON.stringify(data, null, 2));
            })
            .catch((err: unknown) => {
                if (err instanceof Error) {
                    setApiResponse(err.message);
                } else {
                    setApiResponse(String(err));
                }
            });
    };

    return (
        <>
            <div className="page">
                <div className="header">
                    <a
                        className="github"
                        href="https://github.com/ni/systemlink-enterprise-examples/examples/Web Apps/Framework Examples/React/ApiKeyAuthApp/"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span className="title">GitHub</span>
                        <span className="head_text">
                            Link to the GitHub repository with the source code and
                            instructions how to create and use it
                        </span>
                    </a>

                    <a
                        className="Numble"
                        href="https://nimble.ni.dev/"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span className="title">Nimble Design System</span>
                        <span className="head_text">
                            Library with the Nimble components
                        </span>
                    </a>

                    <a
                        className="Swagger"
                        href="https://www.ni.com/docs/en-US/bundle/systemlink-api/page/http-api-reference.html"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span className="title">SystemLink APIs</span>
                        <span className="head_text">
                            Link to the documentation for all SystemLink API calls
                        </span>
                    </a>

                    <a
                        className="npm"
                        href="https://www.npmjs.com/package/@ni/nimble-react"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span className="title">NPM Nimble</span>
                        <span className="head_text">
                            Link to the npm package for Nimble React components
                        </span>
                    </a>

                    <a
                        className="CLI"
                        href="https://github.com/ni-kismet/systemlink-cli"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <span className="title">SystemLink CLI</span>
                        <span className="head_text">
                            Link to the GitHub instructions on how to use the CLI
                        </span>
                    </a>
                </div>

                <div className="content">
                    <div className="button_and_title">
                        <NimbleButton
                            className="button"
                            onClick={handleClick}
                            appearance-variant="accent"
                        >
                            Make API call
                        </NimbleButton>
                    </div>

                    <h2 className="API_title">API call example</h2>

                    <div className="main_description">
                        <div className="API">
                            <div className="API_method_and_path">
                                <span className="method">GET</span>
                                <h3 className="path">/auth</h3>
                            </div>
                            <div>
                                <span className="API_description_title">
                                    Authenticates API Keys
                                </span>
                            </div>
                            <div className="API_description">
                                <span className="API_text">
                                    The example makes an HTTP GET request to a SystemLink API and
                                    displays the result on the page. This specific API
                                    Authenticates the given x-ni-api-key and returns information
                                    about the call.
                                </span>
                            </div>
                            <div className="API_response">{apiResponse}</div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
